/** Bilingual `timeline` messages. Add keys for this area here only. */
export const timelineMessages = {
  'en-us': {
      knowledgeBrand: 'Knowledge', title: 'Timeline', intro: 'Events shown in {timezone}. Occurred, observed, and valid times are separate.',
      dateFrom: 'From date', dateToExclusive: 'To date (exclusive)', source: 'Source', allSources: 'All sources', loadSources: 'Load more sources', sourcesUnavailable: 'Sources are unavailable.',
      entity: 'Entity', allEntities: 'All entities', loadEntities: 'Load more entities', entitiesUnavailable: 'Entities are unavailable.', unnamedEntity: 'Unnamed entity',
      precision: 'Occurrence precision', allPrecision: 'All precision', timed: 'Timed', dateOnly: 'Date only', unknownTime: 'Unknown time', type: 'Event type', typeHelp: 'Matches event types regardless of letter case.', typeTooLong: 'Event type must be 64 characters or fewer.',
      rangeHelp: 'The end date is excluded. Dates filter occurrence time, not a historical graph snapshot; unknown-time events cannot be date-filtered.', timezoneLabel: 'Calendar and display time zone: {timezone}', applyFilters: 'Apply filters', invalidRange: 'Choose both dates and make the end date later than the start date.',
      loading: 'Loading timeline', loadFailed: 'Could not load the timeline.', retry: 'Retry', loadedCount: '{count} matching events loaded', graphStatusUnavailable: 'Graph status unavailable.', graphStatusLoading: 'Loading graph status…', graphStatusNoEvidence: 'No evidence versions to check for graph status.', graphStatusSummary: 'Graph status returned for {count} evidence versions.', graphStatusBound: 'Graph status is checked for the first 100 evidence versions; {count} more are not included.', graphStatusRowsBound: '{count} additional status rows are omitted from this list.', graphStatusDetails: 'Graph synchronization status', graphEnabled: 'enabled', graphDisabled: 'disabled', metadataVersionSnapshot: 'Title and URL are from this document version.', metadataCurrentFallback: 'Title and URL use current document metadata; historical metadata is unavailable.',
      searchActive: 'Showing events matching "{query}".', clearSearch: 'Clear search',
      noEvents: 'No events match these filters.', loadMore: 'Load more events', nextPageFailed: 'Could not load the next timeline page.', occurred: 'Occurred', observed: 'Observed by source', recorded: 'Recorded by Umwelt-OS', validity: 'Valid from – valid to', openStart: 'No start boundary', openEnd: 'No end boundary',
      lateArrival: 'Observed after the recorded occurrence time.', derived: 'Derived', manual: 'Manual', participants: 'Participants', evidence: 'Evidence', evidenceObserved: 'Evidence observed', sourceId: 'Source',
  },
  'vi-vi': {
      knowledgeBrand: 'Tri thức', title: 'Dòng thời gian', intro: 'Sự kiện hiển thị theo múi giờ {timezone}. Thời điểm xảy ra, quan sát và hiệu lực được tách riêng.',
      dateFrom: 'Từ ngày', dateToExclusive: 'Đến ngày (không gồm)', source: 'Nguồn', allSources: 'Tất cả nguồn', loadSources: 'Tải thêm nguồn', sourcesUnavailable: 'Nguồn không khả dụng.',
      entity: 'Thực thể', allEntities: 'Tất cả thực thể', loadEntities: 'Tải thêm thực thể', entitiesUnavailable: 'Thực thể không khả dụng.', unnamedEntity: 'Thực thể chưa có tên',
      precision: 'Độ chính xác thời điểm', allPrecision: 'Tất cả độ chính xác', timed: 'Có giờ', dateOnly: 'Chỉ ngày', unknownTime: 'Chưa rõ thời điểm', type: 'Loại sự kiện', typeHelp: 'Khớp loại sự kiện không phân biệt chữ hoa chữ thường.', typeTooLong: 'Loại sự kiện không được dài quá 64 ký tự.',
      rangeHelp: 'Ngày kết thúc không được tính. Bộ lọc dùng ngày xảy ra, không chọn ảnh chụp lịch sử của đồ thị; sự kiện chưa rõ thời điểm không thể lọc theo ngày.', timezoneLabel: 'Múi giờ lịch và hiển thị: {timezone}', applyFilters: 'Áp dụng bộ lọc', invalidRange: 'Hãy chọn cả hai ngày và đặt ngày kết thúc sau ngày bắt đầu.',
      loading: 'Đang tải dòng thời gian', loadFailed: 'Không thể tải dòng thời gian.', retry: 'Thử lại', loadedCount: 'Đã tải {count} sự kiện phù hợp', graphStatusUnavailable: 'Trạng thái đồ thị chưa khả dụng.', graphStatusLoading: 'Đang tải trạng thái đồ thị…', graphStatusNoEvidence: 'Không có phiên bản bằng chứng để kiểm tra trạng thái đồ thị.', graphStatusSummary: 'Đã nhận trạng thái đồ thị cho {count} phiên bản bằng chứng.', graphStatusBound: 'Chỉ kiểm tra trạng thái đồ thị cho 100 phiên bản bằng chứng đầu tiên; còn {count} phiên bản chưa được tính.', graphStatusRowsBound: 'Còn {count} dòng trạng thái khác không hiển thị trong danh sách này.', graphStatusDetails: 'Trạng thái đồng bộ đồ thị', graphEnabled: 'đã bật', graphDisabled: 'đã tắt', metadataVersionSnapshot: 'Tiêu đề và URL thuộc phiên bản tài liệu này.', metadataCurrentFallback: 'Tiêu đề và URL dùng siêu dữ liệu tài liệu hiện tại; siêu dữ liệu lịch sử chưa khả dụng.',
      searchActive: 'Đang hiển thị sự kiện khớp "{query}".', clearSearch: 'Xóa tìm kiếm',
      noEvents: 'Không có sự kiện phù hợp với bộ lọc.', loadMore: 'Tải thêm sự kiện', nextPageFailed: 'Không thể tải trang dòng thời gian tiếp theo.', occurred: 'Xảy ra lúc', observed: 'Nguồn đã quan sát', recorded: 'Umwelt-OS đã ghi nhận', validity: 'Hiệu lực từ – đến', openStart: 'Không có mốc bắt đầu', openEnd: 'Không có mốc kết thúc',
      lateArrival: 'Được quan sát sau thời điểm xảy ra đã ghi nhận.', derived: 'Suy ra', manual: 'Thủ công', participants: 'Người tham gia', evidence: 'Bằng chứng', evidenceObserved: 'Bằng chứng được quan sát lúc', sourceId: 'Nguồn',
  },
} as const;
