/** Bilingual `topics` messages. Add keys for this area here only. */
export const topicsMessages = {
  'en-us': {
      title: 'Tracked topics', description: 'Manage topic interests used to shape news relevance.', add: 'Add topic', loading: 'Loading…', loadFailed: 'Could not load tracked topics.', empty: 'No topics are being tracked.', edit: 'Edit', delete: 'Delete', activeFor: 'Track {name}', importanceValue: 'Importance: {value}', editTitle: 'Edit topic', createTitle: 'Add a topic', name: 'Name', descriptionField: 'Description', keywords: 'Keywords', keywordBounds: 'Up to 50 comma-separated keywords; each may contain up to 100 characters.', keywordBoundsError: 'Use no more than 50 keywords, with at most 100 characters each.', importance: 'Importance', importanceHint: 'Choose a value from 0 to 10. Higher values indicate stronger interest.', active: 'Track this topic', entities: 'Related entities', searchEntities: 'Search entities by name', entityBounds: '{count}/100 entities selected', removeEntity: 'Remove entity {id}', entitiesFailed: 'Could not load entity options.', conflict: 'This topic changed elsewhere. Reload the current version, then review and save your draft again.', reloadReview: 'Reload current version and review draft', loadingCurrent: 'Loading current version…', reloadFailed: 'Could not reload the current version. Your draft is preserved; retry the reload.', currentServerVersion: 'Current server version · revision {revision}', draftVersion: 'Your unsaved draft', continueAfterReview: 'I reviewed these values — continue', reviewComplete: 'Reviewed revision {revision}. Compare the current values above with your draft before saving.', none: 'None', yes: 'Yes', no: 'No', draftRetained: 'Your unsaved edits have been kept for review.', saveFailed: 'Could not save the topic. Review the fields and try again.', deleteFailed: 'Could not remove the topic. Reload it and try again.', totalCount: 'Showing {loaded} of {total} tracked topics.', loadMore: 'Load more topics', loadingMore: 'Loading more topics…', loadMoreFailed: 'Could not load more topics.', retryLoadMore: 'Retry loading topics', cancel: 'Cancel', save: 'Save', saving: 'Saving…', deleteTitle: 'Remove tracked topic?', deleteDescription: 'Remove {name} from tracked interests? Its profile will be retired and it will no longer shape future tracking.', deleting: 'Removing…', confirmDelete: 'Remove topic',
  },
  'vi-vi': {
      title: 'Chủ đề theo dõi', description: 'Quản lý mối quan tâm dùng để điều chỉnh mức độ liên quan của tin tức.', add: 'Thêm chủ đề', loading: 'Đang tải…', loadFailed: 'Không thể tải danh sách chủ đề.', empty: 'Chưa có chủ đề nào được theo dõi.', edit: 'Chỉnh sửa', delete: 'Xóa', activeFor: 'Theo dõi {name}', importanceValue: 'Mức độ quan tâm: {value}', editTitle: 'Chỉnh sửa chủ đề', createTitle: 'Thêm chủ đề', name: 'Tên', descriptionField: 'Mô tả', keywords: 'Từ khóa', keywordBounds: 'Tối đa 50 từ khóa, phân tách bằng dấu phẩy; mỗi từ khóa tối đa 100 ký tự.', keywordBoundsError: 'Tối đa 50 từ khóa và mỗi từ khóa không quá 100 ký tự.', importance: 'Mức độ quan tâm', importanceHint: 'Chọn giá trị từ 0 đến 10. Giá trị cao hơn thể hiện mức độ quan tâm lớn hơn.', active: 'Theo dõi chủ đề này', entities: 'Thực thể liên quan', searchEntities: 'Tìm thực thể theo tên', entityBounds: 'Đã chọn {count}/100 thực thể', removeEntity: 'Xóa thực thể {id}', entitiesFailed: 'Không thể tải danh sách thực thể.', conflict: 'Chủ đề đã được thay đổi ở nơi khác. Tải phiên bản hiện tại rồi xem lại và lưu bản nháp.', reloadReview: 'Tải lại phiên bản hiện tại và xem bản nháp', loadingCurrent: 'Đang tải phiên bản hiện tại…', reloadFailed: 'Không thể tải lại phiên bản hiện tại. Bản nháp vẫn được giữ; hãy thử tải lại.', currentServerVersion: 'Phiên bản hiện tại trên máy chủ · lần sửa {revision}', draftVersion: 'Bản nháp chưa lưu của bạn', continueAfterReview: 'Tôi đã xem các giá trị này — tiếp tục', reviewComplete: 'Đã xem lần sửa {revision}. Hãy so sánh giá trị hiện tại ở trên với bản nháp trước khi lưu.', none: 'Không có', yes: 'Có', no: 'Không', draftRetained: 'Các thay đổi chưa lưu vẫn được giữ để xem lại.', saveFailed: 'Không thể lưu chủ đề. Hãy kiểm tra trường nhập và thử lại.', deleteFailed: 'Không thể xóa chủ đề. Hãy tải lại và thử lại.', totalCount: 'Đang hiển thị {loaded}/{total} chủ đề.', loadMore: 'Tải thêm chủ đề', loadingMore: 'Đang tải thêm chủ đề…', loadMoreFailed: 'Không thể tải thêm chủ đề.', retryLoadMore: 'Thử tải lại chủ đề', cancel: 'Hủy', save: 'Lưu', saving: 'Đang lưu…', deleteTitle: 'Xóa chủ đề theo dõi?', deleteDescription: 'Xóa {name} khỏi danh sách mối quan tâm? Hồ sơ sẽ được lưu dấu đã xóa và không còn ảnh hưởng đến theo dõi sau này.', deleting: 'Đang xóa…', confirmDelete: 'Xóa chủ đề',
  },
} as const;
